name: Metrics
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@latest
      with:
        plugin_achievements: yes
        plugin_achievements_threshold: B
        plugin_achievements_secrets: yes
        plugin_achievements_ignored: octonaut
        plugin_achievements_limit: 0
