name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bituq
          template: classic
          base: header, activity
          config_timezone: Europe/Amsterdam
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
